# run SPARQL queries for DSMN on new RDF data 

name: SPARQL query checker (step 1 workflow)

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # Run the workflow on the 1st and 15th day of each month
permissions:
  contents: write
  pages: write
  id-token: write
  issues: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  blazegraph-runner:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # step 1: check out the rpository
    - name: Checkout
      uses: actions/checkout@v4
    # step 2: install the blazegraph-runner tool
    - name: install blazegraph runner
      run: |
          sudo apt install wget
          wget https://github.com/balhoff/blazegraph-runner/releases/download/v1.7/blazegraph-runner-1.7.tgz
          tar -xvzf blazegraph-runner-1.7.tgz
          cd ~/blazegraph-runner-1.7/bin
          ls
